### ISSUE TITLE
meb sertifikası

### ISSUE THREAD

**Issue by bayramkarahan** [qr-greeter/devuan-kde#21]
sertifika ekli değil

wget http://sertifika.meb.gov.tr/MEB_SERTIFIKASI.cer -O /tmp/MEB_SERTIFIKASI.cer
openssl x509 -inform DER -in /tmp/MEB_SERTIFIKASI.cer -out /tmp/MEB_SERTIFIKASI.crt
sudo cp /tmp/MEB_SERTIFIKASI.crt /usr/local/share/ca-certificates/MEB_SERTIFIKASI.crt
sudo update-ca-certificates

bu şekilde yaptım olmadı elle tarayıcıdan yükledim

**Comment by bayramkarahan** [comment]
sertifika yüklenmemiş

**Comment by sulincix** [comment]
github actions mebin sitesinden dosyayı çekemiyor.
